// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicollasDavi.Models;

#nullable disable

namespace NicollasDavi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240502123017_Raltion")]
    partial class Raltion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");
#pragma warning restore 612, 618
        }
    }
}
